os:
  - linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - TRAVIS: true

install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - python setup.py install

# build for all pushes, as well as PRs coming from forks
# this ensures that the pipeline is triggered for internal pushes,
# PRs from forks and pushes to existing PRs from forks
if: (type == push) OR (type == pull_request AND fork == true)

script:
  # style tests
  - flake8
  - pylint --rcfile pylint.cfg setup.py zarp/
  - mypy zarp
  # unit tests
  - coverage run --source zarp -m pytest
  - coveralls
  # integration tests
  - zarp --help

after_success:
- git config --global user.name "semantic-release (via TravisCI)"
- git config --global user.email "semantic-release@travis"
- semantic-release publish -v DEBUG
