name: zarp-cli
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - addict >=2.4.0
  - bidict >=0.22.0
  - email-validator >=1.2.1
  - genomepy >=0.15.0
  - jsonref >=0.2
  - numpy >=1.22, <1.25
  - pandas >=1.3.5, <1.4.0
  - pip >=22.1
  - pydantic >=1.9.2, <2.0.0
  - pygments >=2.8.0
  - python >=3.9, <=3.10
  - rich >=12.5.1
  - snakemake >=7.19.1
  - pip:
    - -e ..
