name: zarp-cli
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - addict >=2.4.0
  - bidict >=0.22.0
  - black >=20.8b1
  - coverage>=5.4
  - email-validator >=1.2.1
  - flake8>=3.8.4
  - flake8-docstrings >=1.6.0
  - genomepy >=0.15.0
  - jsonref >=0.2
  - mypy >=0.812
  - numpy >=1.22, <1.25
  - pandas >=1.3.5, <1.4.0
  - pandas-stubs >=1.2.0.62
  - pip >=22.1
  - pydantic >=1.9.2, <2.0.0
  - pygments >=2.8.0
  - pylint >=2.7.1
  - pytest >=6.2.2
  - python >=3.9, <=3.10
  - python-semantic-release >=7.15.0
  - rich >=12.5.1
  - singularity >=3.5
  - snakemake >=7.19.1
  - types-PyYAML >=6.0.11
  - pip:
    - -e ..

