name: static-code-analysis

on: [push, pull_request]

jobs:

  static-code-analysis:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dev dependencies
        run: pip install -r requirements_dev.txt

      - name: Run Flake8
        run: flake8

      - name: Run Pylint
        run: pylint --rcfile pylint.cfg setup.py zarp/

      - name: Run Mypy
        run: mypy zarp
