name: semantic-release

on: [push, pull_request]

jobs:

  publish-debug:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dev dependencies
        run: pip install -r requirements_dev.txt

      - name: Branches
        run: git branch -a

      - name: Publish the package (DEBUG mode)
        run: |
          git config --global user.name "semantic-release (via GH Actions)"
          git config --global user.email "semantic-release@actions"
          semantic-release publish -v DEBUG
