name: tests

on: [push, pull_request]

jobs:

  static-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: check out repository
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install -e .
          pip install -r requirements_dev.txt

      - name: flake8
        run: flake8

      - name: pylint
        run: pylint --rcfile pylint.cfg zarp/

      - name: mypy
        run: mypy zarp

  unit-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    name: unit-testing-Python-${{ matrix.python-version }}

    steps:

      - name: check out repository
        uses: actions/checkout@v2

      - name: install requirements
        run: |
          pip install -e .
          pip install -r requirements_dev.txt

      - name: run unit tests
        run: |
          coverage run --source zarp -m pytest
          coverage xml

      - name: submit coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

  integration-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    name: integration-testing-Python-${{ matrix.python-version }}

    steps:

      - name: check out repository
        uses: actions/checkout@v2

      - name: install requirements
        run: pip install -e .

      - name: integration test - help screen
        run: zarp --help

      - name: integration test - version screen
        run: zarp --version

      - name: set up Conda/Mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          channels: conda-forge
          auto-activate-base: false

      - name: integration test - normal mode
        run: |
          mkdir -p $HOME/.zarp
          export PATH=$PATH:$PWD/bin
          cp tests/files/config_valid.yaml ~/.zarp/user.yaml
          ZARP_REPO_PATH=$HOME/.zarp/workflows
          git clone https://github.com/zavolanlab/zarp.git $ZARP_REPO_PATH
          zarp \
            my_other_sample@tests/files/empty \
            tests/files/empty,tests/files/empty \
            SRR1525892 \
            ERR2248142 \
            table:tests/files/sample_table.tsv \
            NotASample \
            /path/to/* \
            table:$PWD/tests/files/empty \
            --execution-mode=RUN \
            --dependency-embedding=SINGULARITY \
            --working-directory=$HOME/ \
            --zarp-directory=$ZARP_REPO_PATH \
            --verbosity=DEBUG
