name: tests

on: [push, pull_request]

jobs:

  static-code-analysis:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up Miniforge with ZARP-cli environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.dev.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp-cli

      - name: display Conda and environment info
        run: |
          conda info -a
          conda list

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: flake8
        run: flake8

      - name: pylint
        run: pylint --rcfile pylint.cfg zarp/

      - name: mypy
        run: mypy zarp

  unit-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up Miniforge with ZARP-cli environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.dev.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp-cli

      - name: display Conda and environment info
        run: |
          conda info -a
          conda list

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: run unit tests
        run: |
          coverage run --source zarp -m pytest && coverage xml

      - name: submit coverage report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

  integration-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: check out repository
        uses: actions/checkout@v4

      - name: set up Miniforge with ZARP-cli environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: install/environment.dev.yml
          miniforge-version: latest
          conda-remove-defaults: true
          channel-priority: strict
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: zarp-cli

      - name: display Conda and environment info
        run: |
          conda info -a
          conda list

      - name: integration test - help screen
        run: zarp --help

      - name: integration test - version screen
        run: zarp --version
